import { useEffect, useState } from "react";
import CaloriesChart from "../components/CaloriesChart";
import { getDailyHealthTip } from "../utils/healthTips";
import jsPDF from "jspdf";


function History() {
  const [items, setItems] = useState([]);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [mealFilter, setMealFilter] = useState("all");
  const [healthTip, setHealthTip] = useState("");
  const [loading, setLoading] = useState(true);
  const [reportType, setReportType] = useState("weekly"); // weekly | monthly
  const userName = "Pal Anghan";
  // const [email, setEmail] = useState(""); in update can add 



  useEffect(() => {
  window.scrollTo(0 , 0);
}, []);


const fetchHistory = async (p = page) => {
  setLoading(true);
  try {
    const res = await fetch(
      `${import.meta.env.VITE_API_URL}/api/history?page=${p}&limit=5`
    );

    if (!res.ok) {
      
      throw new Error(errText);
    }

    const data = await res.json(); // ✅ correct
    

    setItems(data.data || []);
    setPage(data.page);
    setTotalPages(data.totalPages);
  } catch (err) {
    console.error("History error:", err.message);
  } finally {
    setLoading(false);
  }
};





  useEffect(() => {
    fetchHistory(page);
  }, [page]);

  useEffect(() => {
  setHealthTip(getDailyHealthTip());
}, []);


  const filteredItems = items.filter((item) => {
  if (!fromDate && !toDate) return true;

  const itemDate = new Date(item.createdAt);
  const from = fromDate ? new Date(fromDate) : null;
  const to = toDate ? new Date(toDate) : null;

  if (from && itemDate < from) return false;
  if (to && itemDate > to) return false;

  return true;
});

{/* Date Filter */}
<div className="flex flex-col sm:flex-row gap-4">
  <input
    type="date"
    value={fromDate}
    onChange={(e) => setFromDate(e.target.value)}
    className="border rounded-lg px-3 py-2"
  />
  <input
    type="date"
    value={toDate}
    onChange={(e) => setToDate(e.target.value)}
    className="border rounded-lg px-3 py-2"
  />
</div>

// 2️⃣ Meal filter (FROM filteredItems)
const mealFilteredItems =
  mealFilter === "all"
    ? filteredItems
    : filteredItems.filter(
        (item) => item.mealType === mealFilter
      );



  // 🔢 DAILY SUMMARY CALCULATIONS
const totalCalories = mealFilteredItems.reduce(
  (sum, i) => sum + i.calories,
  0
);


const totalProtein = mealFilteredItems.reduce(
  (sum, i) => sum + (i.protein || 0),
  0
);

const totalItems = mealFilteredItems.length;



const DAILY_GOAL = 2000;
const progressPercent = Math.min((totalCalories / DAILY_GOAL) * 100, 100);



const caloriesPerDay = items.reduce((acc, item) => {
  const date = new Date(item.created_at).toLocaleDateString();

  if (!acc[date]) {
    acc[date] = 0;
  }

  acc[date] += Number(item.calories);
  return acc;
}, {});

const now = new Date();

const reportItems = mealFilteredItems.filter((item) => {
  const itemDate = new Date(item.createdAt);

  if (reportType === "weekly") {
    const weekAgo = new Date();
    weekAgo.setDate(now.getDate() - 7);
    return itemDate >= weekAgo;
  }

  if (reportType === "monthly") {
    return (
      itemDate.getMonth() === now.getMonth() &&
      itemDate.getFullYear() === now.getFullYear()
    );
  }

  return true;
});

const reportCalories = reportItems.reduce(
  (sum, i) => sum + Number(i.calories || 0),
  0
);

const reportProtein = reportItems.reduce(
  (sum, i) => sum + Number(i.protein || 0),
  0
);

const reportMeals = reportItems.length;



  

  const downloadReportPDF = () => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(18);
  doc.text("NutriVision - Nutrition Report", 20, 20);

  // Subtitle
  doc.setFontSize(12);
  doc.text(`User: ${userName}`, 20, 26);
  
  doc.text(
    `${reportType === "weekly" ? "Weekly" : "Monthly"} Report`,
    20,
    30
  );

  doc.text(
    `Generated on: ${new Date().toLocaleDateString()}`,
    20,
    38
  );

  // Line
  doc.line(20, 42, 190, 42);

  // Content
  doc.setFontSize(14);
  doc.text(`🔥 Calories: ${reportCalories} kcal`, 20, 55);
  doc.text(`💪 Protein: ${reportProtein.toFixed(1)} g`, 20, 65);
  doc.text(`🍽️ Meals Logged: ${reportMeals}`, 20, 75);

  // Footer
  doc.setFontSize(10);
  doc.text(
    "Generated by NutriVision AI Food Analyzer",
    20,
    280
  );

  // Save file
  doc.save(
    `nutrivision-${reportType}-report.pdf`
  );
};


  

const handleDelete = async (id) => {
  const confirm = window.confirm("Are you sure?");
  if (!confirm) return;

  try {
    const res = await fetch(
      `${import.meta.env.VITE_API_URL}/api/history/${id}`,
      {
        method: "DELETE",
      }
    );

const text = await res.text();

try {
  const data = JSON.parse(text);
  setItems(data.data);
} catch (e) {
  console.error("Not JSON:", text);
}



    if (!res.ok) {
      console.error(data);
      alert("Delete failed from server");
      return;
    }

    // ✅ Remove from UI
    setItems((prev) => prev.filter((item) => item._id !== id));

  } catch (err) {
    console.error(err);
    alert("Delete failed (network/CORS)");
  }
};

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 to-white px-4 py-10">
    <div className="max-w-4xl mx-auto space-y-8">


      {/* Page Title */}
      <div>
  <h1 className="text-3xl font-bold text-gray-800">
    🍽 Food History
  </h1>
  <p className="text-gray-600 mt-1">
    Track what you’ve eaten and monitor calories  
  </p>
</div>

{/* Meal Type Filter */}
<div className="flex gap-3 mb-6">
  <select
    value={mealFilter}
    onChange={(e) => setMealFilter(e.target.value)}
    className="border rounded-lg px-4 py-2"
  >
    <option value="all">All Meals</option>
    <option value="breakfast">Breakfast</option>
    <option value="lunch">Lunch</option>
    <option value="dinner">Dinner</option>
  </select>
</div>


    {/* Daily Summary */}
<div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
  <div className="bg-white rounded-xl shadow p-4 text-center">
    <p className="text-sm text-gray-500">🔥 Calories</p>
    <p className="text-2xl font-bold text-green-600">{totalCalories} kcal</p>
  </div>

  <div className="bg-white rounded-xl shadow p-4 text-center">
    <p className="text-sm text-gray-500">🥩 Protein</p>
    <p className="text-2xl font-bold text-blue-600">{totalProtein.toFixed(1)} g</p>
  </div>

  <div className="bg-white rounded-xl shadow p-4 text-center">
    <p className="text-sm text-gray-500">🍽 Items</p>
    <p className="text-2xl font-bold text-purple-600">{totalItems}</p>
  </div>
</div>

    {/* Goal Progress */}
<div className="bg-white rounded-xl shadow p-4">
  <div className="flex justify-between mb-1">
    <span className="text-sm font-medium text-gray-700">
      Daily Goal Progress
    </span>
    <span className="text-sm text-gray-600">
      {totalCalories} / {DAILY_GOAL} kcal
    </span>
  </div>

  <div className="w-full bg-gray-200 rounded-full h-3">
    <div
      className={`h-3 rounded-full transition-all duration-700 ease-out ${
        totalCalories <= DAILY_GOAL ? "bg-green-500" : "bg-red-500"
      }`}
      style={{ width: `${progressPercent}%` }}
    />
  </div>
</div>

{/* 🧠 AI Daily Health Tip */}
<div className="bg-white rounded-xl shadow p-5 mt-6 animate-fade">
  <h3 className="text-sm font-semibold text-gray-500 mb-2">
    💡 AI Daily Health Tip
  </h3>
  <p className="text-gray-700 text-base">
    {healthTip}
  </p>
</div>

{/* 📊 Weekly / Monthly Report */}
<div className="bg-white rounded-xl shadow p-5 mt-6 animate-fade">
  <div className="flex justify-between items-center mb-4">
    <h3 className="text-sm font-semibold text-gray-700">
      📅 {reportType === "weekly" ? "Weekly" : "Monthly"} Report
    </h3>

    {/* 📥 Download Button */}
    <button
      onClick={downloadReportPDF}
      className="bg-green-600 text-white px-3 py-1 rounded-lg text-sm hover:bg-green-700"
    >
      ⬇ PDF
    </button>

    <select
      value={reportType}
      onChange={(e) => setReportType(e.target.value)}
      className="border rounded-lg px-2 py-1 text-sm"
    >
      <option value="weekly">Weekly</option>
      <option value="monthly">Monthly</option>
    </select>
  </div>

  <div className="grid grid-cols-3 gap-4 text-center">
    <div>
      <p className="text-xs text-gray-500">Calories</p>
      <p className="font-bold text-green-600">{reportCalories} kcal</p>
    </div>

    <div>
      <p className="text-xs text-gray-500">Protein</p>
      <p className="font-bold text-blue-600">{reportProtein.toFixed(1)} g</p>
    </div>

    <div>
      <p className="text-xs text-gray-500">Meals</p>
      <p className="font-bold text-purple-600">{reportMeals}</p>
    </div>
  </div>
</div>





      {/* Chart Card */}
      <div className="bg-white rounded-2xl shadow-md p-6">
  <h2 className="text-lg font-semibold mb-4">
    📊 Calories Per Day
  </h2>
  <CaloriesChart history={mealFilteredItems} dailyGoal={2000} />
</div>

  
   {/* History Cards */}
<div className="space-y-4">

  {/* Skeleton Loader */}
  {loading && (
    [...Array(3)].map((_, i) => (
      <div
        key={i}
        className="bg-white rounded-xl shadow p-5 animate-pulse"
      >
        <div className="h-4 bg-gray-200 rounded w-1/3 mb-3"></div>
        <div className="h-3 bg-gray-200 rounded w-1/2 mb-2"></div>
        <div className="h-3 bg-gray-200 rounded w-1/4"></div>
      </div>
    ))
  )}

  {/* Empty State */}
  {!loading && mealFilteredItems.length === 0 && (
    <div className="text-center py-12 bg-white rounded-xl shadow">
      <div className="text-5xl mb-3">🍽️</div>
      <h3 className="text-lg font-semibold text-gray-700">
        No meals found
      </h3>
      <p className="text-gray-500 mt-1">
        Upload a food image to see history here
      </p>
    </div>
  )}

  {/* Actual Cards (WITH DELETE BUTTON) */}
  {!loading && mealFilteredItems.length > 0 &&
    mealFilteredItems.map((item) => (
      <div
        key={item._id}
        className="bg-white rounded-xl shadow p-5 flex justify-between items-center"
      >
        <div>
          <h3 className="font-semibold capitalize">{item.food}</h3>
          <p className="text-sm text-gray-600">
            🔥 {item.calories} kcal · 💪 {item.protein} g
          </p>
          <span className="text-xs bg-green-100 text-green-700 px-2 py-1 rounded-full">
            {item.mealType}
          </span>
        </div>

        {/* ✅ DELETE BUTTON */}
        <button
          onClick={() => handleDelete(item._id)}
          className="text-red-500 hover:text-red-700 text-sm font-medium"
        >
          ❌ Delete
        </button>
      </div>
    ))
  }
</div>




      {/* Pagination */}
 <div   className="flex justify-between items-center pt-6">
  <button
    disabled={page === 1}
    onClick={() => setPage(page - 1)}
    className="px-4 py-2 bg-gray-200 rounded-lg disabled:opacity-50"
  >
    ← Prev
  </button>

  <span className="font-medium">
    Page {page} / {totalPages}
  </span>

  <button
    disabled={page === totalPages}
    onClick={() => setPage(page + 1)}
    className="px-4 py-2 bg-gray-200 rounded-lg disabled:opacity-50"
  >
    Next →
  </button>
</div>


    </div>
  </div>
);

}

export default History;
